"""Step A — real passing networks (Section 12, Layer 5).

Accumulates one team's completed passes across a full-league season and builds
its interaction network, then reads off the collective properties with the
already-validated `players.passing_network` / `critical_links` and
`tactical.team_robustness` / `dependence_on_key_players`. The most-central players
and strongest links double as a sanity check.
"""

from __future__ import annotations

import argparse
import os

from fie import db as fie_db
from fie.players import critical_links, passing_network
from fie.sources.statsbomb import StatsBombSource, passing_records
from fie.tactical import cohesion, dependence_on_key_players, fluidity, team_robustness

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=11)
    ap.add_argument("--season", type=int, default=27)
    ap.add_argument("--team", default="Barcelona")
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--db", default="fie_real.sqlite")
    ap.add_argument("--out", default="validation/results/RESULTS_NETWORK.md")
    args = ap.parse_args()

    source = StatsBombSource(args.competition, args.season, cache_dir=args.cache)
    team_matches = [
        m for m in source.matches()
        if args.team in (m["home_team"]["home_team_name"], m["away_team"]["away_team_name"])
    ]
    print(f"{args.team}: {len(team_matches)} matches in competition "
          f"{args.competition}/{args.season}")

    names = {}
    records = []
    used = 0
    for m in team_matches:
        try:
            raw = source.raw_events(m["match_id"])
        except Exception as exc:  # noqa: BLE001
            print(f"  match {m['match_id']}: skipped ({exc})")
            continue
        records.extend(passing_records(raw, args.team, names))
        used += 1

    graph = passing_network(records)
    if not graph:
        raise SystemExit("No passing data (matches not cached?).")

    # Strongest connections and most-central players.
    strongest = sorted(graph.items(), key=lambda kv: kv[1]["weight"], reverse=True)[:10]
    central = critical_links(graph, top=8)

    scope = f"{args.team} {args.competition}/{args.season}"
    conn = fie_db.connect(args.db)
    fie_db.init_schema(conn)
    fie_db.insert_interactions(conn, scope, graph, names)

    lines = [
        f"# RESULTS (network) — {args.team} passing network (Section 12, Layer 5)",
        "",
        f"> Generated by `scripts/build_networks.py` over {used} {args.team} matches "
        f"(competition {args.competition}, season {args.season}). Edges persisted to "
        "SQLite `interactions`.",
        "",
        f"- Directed edges: **{len(graph)}**",
        f"- Robustness (1 − concentration): **{team_robustness(graph):.3f}**",
        f"- Dependence on key players (busiest node share): "
        f"**{dependence_on_key_players(graph):.3f}**",
        f"- Cohesion: {cohesion(graph):.3f}   |   Fluidity: {fluidity(graph):.3f}",
        "",
        "## Most central players (busiest in the network)",
        "",
        "| Rank | Player |",
        "|---|---|",
    ]
    for i, pid in enumerate(central, 1):
        lines.append(f"| {i} | {names.get(pid, pid)} |")

    lines += ["", "## Strongest passing links", "", "| From | To | Passes | Chances |", "|---|---|---|---|"]
    for (a, b), d in strongest:
        lines.append(f"| {names.get(a, a)} | {names.get(b, b)} | {d['weight']} | {d['chances']} |")
    lines += [
        "",
        "> The network is the substrate of Collective Intelligence (Section 14): a "
        "team whose chances all flow through one link is fragile; many redundant "
        "connections make it robust. Central players and strong links should match "
        "how the team actually builds play.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\n" + "\n".join(lines[4:10]))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
