"""Step B — on/off player influence (Section 12, Layer 4).

For one team, reconstruct each player's minutes on the pitch across a season and
compare the team's goals-per-90 with that player on vs off. A descriptive on/off
estimate — NOT causal: a player can look influential only because he comes on (or
starts) in favorable game states (Section 12's confounder warning). Minutes are
reported as the reliability measure.
"""

from __future__ import annotations

import argparse
import os

from fie import db as fie_db
from fie.players import goal_influence
from fie.sources.statsbomb import StatsBombSource, match_on_off

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)

MIN_ON_MINUTES = 270.0   # ~3 full matches on the pitch
MIN_OFF_MINUTES = 90.0   # ~1 full match off the pitch (so lambda_off is meaningful)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=11)
    ap.add_argument("--season", type=int, default=27)
    ap.add_argument("--team", default="Barcelona")
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--db", default="fie_real.sqlite")
    ap.add_argument("--out", default="validation/results/RESULTS_INFLUENCE.md")
    args = ap.parse_args()

    source = StatsBombSource(args.competition, args.season, cache_dir=args.cache)
    team_matches = [
        m for m in source.matches()
        if args.team in (m["home_team"]["home_team_name"], m["away_team"]["away_team_name"])
    ]

    acc = {}
    used = 0
    for m in team_matches:
        try:
            report = match_on_off(source.raw_events(m["match_id"]), args.team)
        except Exception as exc:  # noqa: BLE001
            print(f"  match {m['match_id']}: skipped ({exc})")
            continue
        used += 1
        for pid, d in report["per_player"].items():
            a = acc.setdefault(
                pid,
                {"name": d["name"], "on_min": 0.0, "goals_on": 0, "match_min": 0.0, "team_goals": 0},
            )
            a["on_min"] += d["on_min"]
            a["goals_on"] += d["goals_on"]
            a["match_min"] += report["match_end"]
            a["team_goals"] += report["team_goals"]
            if d["name"]:
                a["name"] = d["name"]

    rows = []
    for pid, a in acc.items():
        off_min = a["match_min"] - a["on_min"]
        if a["on_min"] < MIN_ON_MINUTES or off_min < MIN_OFF_MINUTES:
            continue
        goals_off = a["team_goals"] - a["goals_on"]
        lam_on = a["goals_on"] / a["on_min"] * 90.0    # team goals per 90 with player on
        lam_off = goals_off / off_min * 90.0           # ... with player off
        rows.append(
            {
                "player_id": pid, "name": a["name"], "team": args.team,
                "lambda_on": lam_on, "lambda_off": lam_off,
                "delta": goal_influence(lam_on, lam_off),
                "on_minutes": a["on_min"], "off_minutes": off_min,
            }
        )
    rows.sort(key=lambda r: r["delta"], reverse=True)

    conn = fie_db.connect(args.db)
    fie_db.init_schema(conn)
    fie_db.insert_influence(conn, rows)

    def table(sel):
        out = ["| Player | λon (goals/90) | λoff | Δ | on min | off min |",
               "|---|---|---|---|---|---|"]
        for r in sel:
            out.append(
                f"| {r['name']} | {r['lambda_on']:.2f} | {r['lambda_off']:.2f} | "
                f"{r['delta']:+.2f} | {r['on_minutes']:.0f} | {r['off_minutes']:.0f} |"
            )
        return out

    lines = [
        f"# RESULTS (influence) — {args.team} on/off (Section 12, Layer 4)",
        "",
        f"> Generated by `scripts/build_influence.py` over {used} {args.team} matches "
        f"(competition {args.competition}, season {args.season}). Descriptive on/off, "
        f"not causal. Qualified players: on >= {MIN_ON_MINUTES:.0f} and off >= "
        f"{MIN_OFF_MINUTES:.0f} minutes. Persisted to SQLite `influence`.",
        "",
        f"- Qualified players: **{len(rows)}**",
        "",
        "## Most positive on/off influence (team scores more with them on)",
        "",
    ]
    lines += table(rows[:10])
    lines += ["", "## Most negative on/off influence", ""]
    lines += table(rows[-8:][::-1])
    lines += [
        "",
        "> **Read this as the confounder in action, not a ranking of ability.** Naive "
        "on/off inverts here: rotation players who enter against tiring or weaker "
        "sides top the list, while core starters can show a *negative* delta because "
        "they are rested exactly when the team is already winning big (so it scores "
        "freely without them). This is precisely Section 12's warning that a player "
        "can look influential only because of the game states he plays in — a serious "
        "estimate must control for context (opponent, score, minute). Δ is a weak "
        "descriptive signal weighted by minutes, nothing more.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\n".join(lines[4:6]))
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
