"""Step 3 — build player DNA profiles from finished real matches (Section 12).

Accumulates per-player on-ball events across a whole competition, derives each
player's profile (rates, shares, archetype, avatar), persists them to SQLite, and
writes a report whose top lists double as a sanity check (do the top scorers /
creators look right?).
"""

from __future__ import annotations

import argparse
import os
from collections import Counter

from fie import db as fie_db
from fie.profiling import build_profiles
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def _table(profiles, cols, headers, key, top=10):
    rows = sorted(profiles, key=key, reverse=True)[:top]
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for p in rows:
        lines.append("| " + " | ".join(str(c(p)) for c in cols) + " |")
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=43)
    ap.add_argument("--season", type=int, default=3)
    ap.add_argument("--limit", type=int, default=64)
    ap.add_argument("--min-actions", type=int, default=60)
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--db", default="fie_real.sqlite")
    ap.add_argument("--out", default="validation/results/RESULTS_PROFILES.md")
    args = ap.parse_args()

    source = StatsBombSource(args.competition, args.season, cache_dir=args.cache)
    raw = sorted(source.matches(), key=lambda m: m.get("match_date") or "")[: args.limit]
    print(f"Accumulating player stats over {len(raw)} matches ...")

    table = {}
    used = 0
    for i, rm in enumerate(raw, 1):
        try:
            source.player_stats(rm["match_id"], table)
            used += 1
        except Exception as exc:  # noqa: BLE001
            print(f"  [{i}/{len(raw)}] match {rm['match_id']}: skipped ({exc})")
    profiles = build_profiles(table)
    ranked = [p for p in profiles if p["actions"] >= args.min_actions]
    print(f"Built {len(profiles)} profiles ({len(ranked)} with >= {args.min_actions} actions).")

    conn = fie_db.connect(args.db)
    fie_db.init_schema(conn)
    fie_db.insert_player_profiles(conn, profiles)

    dist = Counter(p["archetype"] for p in profiles)
    lines = [
        "# RESULTS (profiles) — player DNA from real matches (Section 12)",
        "",
        f"> Generated by `scripts/build_profiles.py` on competition {args.competition}, "
        f"season {args.season} ({used} matches). Profiles persisted to SQLite "
        "`player_profiles`.",
        "",
        f"- Players profiled: **{len(profiles)}** "
        f"({len(ranked)} with >= {args.min_actions} on-ball actions)",
        "- Archetype distribution: "
        + ", ".join(f"{k} {v}" for k, v in dist.most_common()),
        "",
        "## Top scorers (sanity check)",
        "",
    ]
    lines += _table(
        ranked,
        [lambda p: p["name"], lambda p: p["team"], lambda p: p["goals"],
         lambda p: p["shots"], lambda p: f"{p['shot_share']:.3f}", lambda p: p["archetype"]],
        ["Player", "Team", "Goals", "Shots", "Shot share", "Archetype"],
        key=lambda p: p["goals"],
    )
    lines += ["", "## Top creators (key-pass rate, >= 100 passes)", ""]
    creators = [p for p in ranked if p["passes"] >= 100]
    lines += _table(
        creators,
        [lambda p: p["name"], lambda p: p["team"], lambda p: f"{p['key_pass_rate']:.3f}",
         lambda p: p["assists"], lambda p: f"{p['progressive_pass_share']:.2f}",
         lambda p: p["archetype"]],
        ["Player", "Team", "Key-pass rate", "Assists", "Progressive share", "Archetype"],
        key=lambda p: p["key_pass_rate"],
    )
    lines += [
        "",
        "> Archetypes are descriptive labels read from observed shares, not ground "
        "truth (Section 12's honest-data warning). Volume (on-ball actions) is the "
        "reliability measure; low-minute players fall to `insufficient_data`.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\n" + "\n".join(lines[4:8]))
    print(f"\nWrote {args.out} and {args.db}")


if __name__ == "__main__":
    main()
