"""Step D — learned model vs heuristic, walk-forward (Section 21, Stage 3).

For each expanding past window: fit the heuristic (base_rate/tau) and train the
logistic model, then score both on the next block of future matches. Reports
whether the learned model beats the heuristic out of sample — honestly, whatever
the answer.
"""

from __future__ import annotations

import argparse
import os

from fie.learned import evaluate_model, train_model
from fie.learning import DEFAULT_TAU_GRID, evaluate, fit_parameters, walk_forward_split
from fie.prediction import Params
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def load_matches(competition, season, cache_dir, limit):
    source = StatsBombSource(competition, season, cache_dir=cache_dir)
    raw = sorted(source.matches(), key=lambda m: m.get("match_date") or "")[:limit]
    out = []
    for rm in raw:
        try:
            out.append(source.match(rm["match_id"]))
        except Exception as exc:  # noqa: BLE001
            print(f"  match {rm['match_id']}: skipped ({exc})")
    out.sort(key=lambda m: (m.get("match_date") or "", m["match_id"]))
    return out


def _weighted(folds, layer, field):
    num = sum(f[layer][field] * f[layer]["n"] for f in folds)
    den = sum(f[layer]["n"] for f in folds)
    return num / den if den else float("nan")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=43)
    ap.add_argument("--season", type=int, default=3)
    ap.add_argument("--limit", type=int, default=64)
    ap.add_argument("--folds", type=int, default=4)
    ap.add_argument("--window", type=int, default=10)
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--out", default="validation/results/RESULTS_LEARNED.md")
    args = ap.parse_args()

    params0 = Params()
    matches = load_matches(args.competition, args.season, args.cache, args.limit)
    print(f"Loaded {len(matches)} matches. Walk-forward ({args.folds} folds) ...")

    key = lambda m: (m.get("match_date") or "", m["match_id"])
    folds = []
    for train, test in walk_forward_split(matches, n_folds=args.folds, key=key):
        fitted = fit_parameters(train, params0, tau_grid=DEFAULT_TAU_GRID, window=args.window)
        model = train_model(train, params0, window=args.window)
        folds.append(
            {
                "untuned": evaluate(test, params0, window=args.window),
                "heuristic": evaluate(test, fitted, window=args.window),
                "learned": evaluate_model(model, test, params0, window=args.window),
            }
        )
    if not folds:
        raise SystemExit("Not enough matches for the requested number of folds.")

    rows = [
        ("Untuned heuristic", "untuned"),
        ("Fitted heuristic (base_rate/tau)", "heuristic"),
        ("Learned logistic model", "learned"),
    ]
    lines = [
        "# RESULTS (learned) — Stage 3 model vs heuristic (Section 21)",
        "",
        f"> Generated by `scripts/fit_learned_statsbomb.py` on competition "
        f"{args.competition}, season {args.season} ({len(matches)} matches, "
        f"{len(folds)} folds). Held-out (future-block) metrics, walk-forward.",
        "",
        "| Model | Held-out log loss | Brier |",
        "|---|---|---|",
    ]
    for label, layer in rows:
        lines.append(
            f"| {label} | {_weighted(folds, layer, 'log_loss'):.4f} | "
            f"{_weighted(folds, layer, 'brier'):.4f} |"
        )

    heuristic_ll = _weighted(folds, "heuristic", "log_loss")
    learned_ll = _weighted(folds, "learned", "log_loss")
    beats = learned_ll < heuristic_ll
    lines += [
        "",
        "## Verdict",
        "",
        f"- Learned model beats the fitted heuristic out of sample: **{beats}** "
        f"({heuristic_ll:.4f} vs {learned_ll:.4f}).",
        "",
    ]
    if beats:
        lines.append(
            "> The logistic model extracts signal from the state features (pressure, "
            "momentum, time, score, recent shots) beyond the heuristic intensity, and "
            "it generalizes to future matches."
        )
    else:
        lines.append(
            "> The learned model does not beat the fitted heuristic here. With this "
            "feature set and sample size the hand-built intensity is already near the "
            "achievable signal; a learned model only earns its place when it beats the "
            "heuristic out of sample (Section 21) — and it must be re-checked as more "
            "data and richer features (e.g. player avatars) are added."
        )
    lines.append("")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\n" + "\n".join(lines[4:11]))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
