"""Multi-target validation — corners and cards in-play (Section 8.3).

Extends the real-data calibration beyond goals: for each target ("corner in the
next 10 minutes", "card in the next 10 minutes"), a walk-forward backtest
compares two leakage-safe predictors:

  1. constant Poisson rate      — lambda fit on past matches only
  2. pressure-scaled rate       — the same lambda scaled by current total
                                  offensive pressure relative to its training
                                  mean (does in-play state help these targets?)

Honest question, honest answer: whichever wins held-out, gets reported.
"""

from __future__ import annotations

import argparse
import math
import os

from fie.calibration import brier, log_loss
from fie.indices import offensive_pressure
from fie.learning import walk_forward_split
from fie.prediction import Params
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)

TARGETS = {
    "corner": ("corner",),
    "card": ("yellow_card", "red_card"),
}
SCALE_CLAMP = (0.25, 4.0)


def load_matches(competition, season, cache_dir, limit):
    source = StatsBombSource(competition, season, cache_dir=cache_dir)
    raw = sorted(source.matches(), key=lambda m: m.get("match_date") or "")[:limit]
    out = []
    for rm in raw:
        try:
            out.append(source.match(rm["match_id"]))
        except Exception as exc:  # noqa: BLE001
            print(f"  match {rm['match_id']}: skipped ({exc})")
    out.sort(key=lambda m: (m.get("match_date") or "", m["match_id"]))
    return out


def snapshots(match, types, params, window, eval_step=5):
    """Leakage-safe per-minute records: (pressure_total, happened)."""
    events = sorted(match["events"], key=lambda e: e.minute)
    duration = int(match.get("duration", 90))
    for t in range(eval_step, max(eval_step, duration - window) + 1, eval_step):
        events_until = [e for e in events if e.minute <= t]
        pressure = offensive_pressure(events_until, "HOME", t, params.tau) + \
            offensive_pressure(events_until, "AWAY", t, params.tau)
        happened = 1 if any(
            e.type in types and t < e.minute <= t + window for e in events
        ) else 0
        yield pressure, happened


def fit_rate(matches, types, window):
    """lambda (events/min) + mean snapshot pressure, from training matches."""
    n_events = sum(
        1 for m in matches for e in m["events"] if e.type in types
    )
    total_minutes = sum(m.get("duration", 90) for m in matches)
    lam = n_events / max(1.0, total_minutes)
    pressures = [p for m in matches for p, _ in snapshots(m, types, Params(), window)]
    mean_pressure = sum(pressures) / max(1, len(pressures))
    return lam, mean_pressure


def evaluate_fold(train, test, types, window):
    lam, mean_pressure = fit_rate(train, types, window)
    const_pairs, scaled_pairs = [], []
    for m in test:
        for pressure, happened in snapshots(m, types, Params(), window):
            p_const = 1 - math.exp(-lam * window)
            scale = min(SCALE_CLAMP[1], max(SCALE_CLAMP[0], pressure / mean_pressure))
            p_scaled = 1 - math.exp(-lam * scale * window)
            const_pairs.append((p_const, happened))
            scaled_pairs.append((p_scaled, happened))
    return const_pairs, scaled_pairs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=11)
    ap.add_argument("--season", type=int, default=27)
    ap.add_argument("--limit", type=int, default=380)
    ap.add_argument("--folds", type=int, default=4)
    ap.add_argument("--window", type=int, default=10)
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--out", default="validation/results/RESULTS_TARGETS.md")
    args = ap.parse_args()

    matches = load_matches(args.competition, args.season, args.cache, args.limit)
    print(f"Loaded {len(matches)} matches.")
    key = lambda m: (m.get("match_date") or "", m["match_id"])

    lines = [
        "# RESULTS (targets) — corners and cards in-play (Section 8.3)",
        "",
        f"> Generated by `scripts/fit_targets_statsbomb.py` on competition "
        f"{args.competition}, season {args.season} ({len(matches)} matches, "
        f"{args.folds}-fold walk-forward, {args.window}-min window). Held-out only.",
        "",
    ]

    for label, types in TARGETS.items():
        const_all, scaled_all = [], []
        for train, test in walk_forward_split(matches, n_folds=args.folds, key=key):
            c, s = evaluate_fold(train, test, types, args.window)
            const_all.extend(c)
            scaled_all.extend(s)
        freq = sum(h for _, h in const_all) / len(const_all)
        lines += [
            f"## Target: {label} in next {args.window} min",
            "",
            f"- Held-out snapshots: {len(const_all)} · observed frequency "
            f"**{freq:.3f}**",
            "",
            "| Predictor | Brier | Log loss |",
            "|---|---|---|",
            f"| Constant Poisson rate (train-fit) | {brier(const_all):.4f} | "
            f"{log_loss(const_all):.4f} |",
            f"| Pressure-scaled rate | {brier(scaled_all):.4f} | "
            f"{log_loss(scaled_all):.4f} |",
            "",
        ]
        better = log_loss(scaled_all) < log_loss(const_all)
        lines.append(
            f"In-play pressure {'**improves**' if better else 'does **not** improve'} "
            f"held-out log loss for this target."
        )
        lines.append("")
        print(f"{label}: freq={freq:.3f} const={log_loss(const_all):.4f} "
              f"scaled={log_loss(scaled_all):.4f} in-play helps: {better}")

    lines += [
        "> Corners and cards were previously engine-only formulas with no "
        "real-data score; this closes that gap. The pressure-scaled variant tests "
        "whether in-play state carries signal for these targets beyond the base "
        "rate — the verdicts above are whatever the held-out data said.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
