"""Phase 3-4 — walk-forward fit of BASE_RATE / TAU on real StatsBomb data.

Loads a competition/season, orders the matches by date, and runs a walk-forward
evaluation: on each expanding past window it fits ``base_rate`` and ``tau`` to
minimize log loss, then measures the *held-out* calibration on the next block of
future matches. This is the honest test that per-competition tuning closes the
over-prediction the untuned engine showed — without overfitting.

Usage:
    python scripts/fit_statsbomb.py --competition 43 --season 3 --limit 64 --folds 4
"""

from __future__ import annotations

import argparse
import os

from fie.learning import DEFAULT_TAU_GRID, walk_forward_report
from fie.prediction import Params
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def _weighted(folds, side, field):
    num = sum(f[side][field] * f[side]["n"] for f in folds)
    den = sum(f[side]["n"] for f in folds)
    return num / den if den else float("nan")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=43)
    ap.add_argument("--season", type=int, default=3)
    ap.add_argument("--limit", type=int, default=64)
    ap.add_argument("--folds", type=int, default=4)
    ap.add_argument("--window", type=int, default=10)
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--out", default="validation/results/RESULTS_FIT.md")
    args = ap.parse_args()

    params0 = Params()
    source = StatsBombSource(args.competition, args.season, cache_dir=args.cache)
    raw = sorted(source.matches(), key=lambda m: m.get("match_date") or "")[: args.limit]
    print(f"Loading {len(raw)} matches (competition {args.competition}, season {args.season}) ...")

    matches = []
    for i, rm in enumerate(raw, 1):
        mid = rm["match_id"]
        try:
            matches.append(source.match(mid))
        except Exception as exc:  # noqa: BLE001
            print(f"  [{i}/{len(raw)}] match {mid}: download failed ({exc}); skipping")
    matches.sort(key=lambda m: m.get("match_date") or "")
    print(f"Loaded {len(matches)} matches. Running {args.folds}-fold walk-forward ...")

    folds = walk_forward_report(
        matches, params0, n_folds=args.folds,
        key=lambda m: (m.get("match_date") or "", m["match_id"]),
        tau_grid=DEFAULT_TAU_GRID, window=args.window,
    )
    if not folds:
        raise SystemExit("Not enough matches for the requested number of folds.")

    b_brier = _weighted(folds, "baseline", "brier")
    f_brier = _weighted(folds, "fitted", "brier")
    b_loss = _weighted(folds, "baseline", "log_loss")
    f_loss = _weighted(folds, "fitted", "log_loss")
    b_pred = _weighted(folds, "baseline", "mean_pred")
    f_pred = _weighted(folds, "fitted", "mean_pred")
    base_freq = _weighted(folds, "baseline", "base_freq")  # observed, same for both

    lines = [
        "# RESULTS (fit) — walk-forward BASE_RATE / TAU on real data (Section 21)",
        "",
        f"> Generated by `scripts/fit_statsbomb.py` on competition {args.competition}, "
        f"season {args.season} ({len(matches)} matches, {len(folds)} folds, "
        f'"goal in next {args.window} min"). Held-out (future-block) metrics only.',
        "",
        f"- Untuned params: base_rate={params0.base_rate}, tau={params0.tau}",
        f"- Observed held-out event frequency: **{base_freq:.3f}**",
        "",
        "| | Mean predicted | Brier | Log loss |",
        "|---|---|---|---|",
        f"| **Untuned** | {b_pred:.3f} | {b_brier:.4f} | {b_loss:.4f} |",
        f"| **Fitted (walk-forward)** | {f_pred:.3f} | {f_brier:.4f} | {f_loss:.4f} |",
        "",
        f"Over-prediction gap |mean_pred − observed|: "
        f"**{abs(b_pred - base_freq):.3f} → {abs(f_pred - base_freq):.3f}**",
        "",
        "## Per-fold fitted parameters (train on past, test on future)",
        "",
        "| Fold | n_train | n_test | fitted base_rate | fitted tau | "
        "held-out log loss (untuned → fitted) |",
        "|---|---|---|---|---|---|",
    ]
    for i, f in enumerate(folds, 1):
        lines.append(
            f"| {i} | {f['n_train']} | {f['n_test']} | {f['fitted_base_rate']} | "
            f"{f['fitted_tau']} | {f['baseline']['log_loss']:.4f} → "
            f"{f['fitted']['log_loss']:.4f} |"
        )
    lines += [
        "",
        "> Walk-forward means the parameters are always fit on matches strictly "
        "*before* the ones they are scored on, so any improvement is out-of-sample "
        "insight, not overfitting.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print("\n" + "\n".join(lines[4:16]))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
