"""Step 2 — per-regime calibration on real data (Section 20/9).

Walk-forward, three layers stacked: untuned -> fit base_rate/tau -> then fit a
per-regime lambda scale. Each layer is fit only on past matches and scored on the
next block of future matches, so the reported gains are out-of-sample. Also prints
the per-regime scales fit on the full dataset, to see how the model reweights each
game state.
"""

from __future__ import annotations

import argparse
import os
from collections import defaultdict

from fie.calibration import iter_match_snapshots
from fie.learning import (
    DEFAULT_TAU_GRID,
    evaluate,
    fit_parameters,
    fit_regime_scale,
    walk_forward_split,
)
from fie.prediction import Params
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def load_matches(competition, season, cache_dir, limit):
    source = StatsBombSource(competition, season, cache_dir=cache_dir)
    raw = sorted(source.matches(), key=lambda m: m.get("match_date") or "")[:limit]
    out = []
    for rm in raw:
        try:
            out.append(source.match(rm["match_id"]))
        except Exception as exc:  # noqa: BLE001
            print(f"  match {rm['match_id']}: skipped ({exc})")
    out.sort(key=lambda m: (m.get("match_date") or "", m["match_id"]))
    return out


def _weighted(folds, layer, field):
    num = sum(f[layer][field] * f[layer]["n"] for f in folds)
    den = sum(f[layer]["n"] for f in folds)
    return num / den if den else float("nan")


def _regime_counts(matches, params, window):
    counts = defaultdict(int)
    for match in matches:
        for snap in iter_match_snapshots(match, params, window):
            counts[snap["regime"]] += 1
    return counts


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=43)
    ap.add_argument("--season", type=int, default=3)
    ap.add_argument("--limit", type=int, default=64)
    ap.add_argument("--folds", type=int, default=4)
    ap.add_argument("--window", type=int, default=10)
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--out", default="RESULTS_REGIME.md")
    args = ap.parse_args()

    params0 = Params()
    matches = load_matches(args.competition, args.season, args.cache, args.limit)
    print(f"Loaded {len(matches)} matches. Walk-forward ({args.folds} folds) ...")

    key = lambda m: (m.get("match_date") or "", m["match_id"])
    folds = []
    for train, test in walk_forward_split(matches, n_folds=args.folds, key=key):
        p1 = fit_parameters(train, params0, tau_grid=DEFAULT_TAU_GRID, window=args.window)
        p2 = fit_regime_scale(train, p1, window=args.window)
        folds.append(
            {
                "untuned": evaluate(test, params0, window=args.window),
                "base_tau": evaluate(test, p1, window=args.window),
                "regime": evaluate(test, p2, window=args.window),
            }
        )
    if not folds:
        raise SystemExit("Not enough matches for the requested number of folds.")

    # Per-regime scales fit on the whole dataset (for display).
    base_full = fit_parameters(matches, params0, tau_grid=DEFAULT_TAU_GRID, window=args.window)
    full = fit_regime_scale(matches, base_full, window=args.window)
    counts = _regime_counts(matches, base_full, args.window)

    lines = [
        "# RESULTS (regime) — per-regime calibration (Section 20/9)",
        "",
        f"> Generated by `scripts/fit_regime_statsbomb.py` on competition "
        f"{args.competition}, season {args.season} ({len(matches)} matches, "
        f"{len(folds)} folds). Held-out (future-block) log loss, walk-forward.",
        "",
        "## Held-out log loss by calibration layer",
        "",
        "| Layer | Log loss | Brier |",
        "|---|---|---|",
        f"| Untuned | {_weighted(folds, 'untuned', 'log_loss'):.4f} | "
        f"{_weighted(folds, 'untuned', 'brier'):.4f} |",
        f"| + base_rate/tau | {_weighted(folds, 'base_tau', 'log_loss'):.4f} | "
        f"{_weighted(folds, 'base_tau', 'brier'):.4f} |",
        f"| + per-regime scale | {_weighted(folds, 'regime', 'log_loss'):.4f} | "
        f"{_weighted(folds, 'regime', 'brier'):.4f} |",
        "",
        f"Fitted base params on full data: base_rate={base_full.base_rate}, "
        f"tau={base_full.tau}",
        "",
        "## Per-regime lambda scale (fit on full data)",
        "",
        "| Regime | Snapshots | Fitted scale |",
        "|---|---|---|",
    ]
    for regime in sorted(full.regime_scale):
        lines.append(
            f"| {regime} | {counts.get(regime, 0)} | {full.regime_scale[regime]} |"
        )

    base_ll = _weighted(folds, "base_tau", "log_loss")
    regime_ll = _weighted(folds, "regime", "log_loss")
    helped = regime_ll < base_ll
    lines += [
        "",
        "## Verdict",
        "",
        f"- Per-regime scale improves held-out log loss over base_rate/tau alone: "
        f"**{helped}** ({base_ll:.4f} -> {regime_ll:.4f}).",
        "",
    ]
    if helped:
        lines.append(
            "> The regime label carries goal-rate information beyond the base "
            "multipliers, and the per-regime scale captures it out of sample."
        )
    else:
        lines.append(
            "> Adding a per-regime lambda scale does **not** help — held-out log loss "
            "rises. On the full data every regime's best scale is ~1.0, meaning the "
            "base multipliers (pressure, score, time, cards) already encode what the "
            "regime label would add; the extra per-regime freedom just overfits the "
            "training folds. This is exactly Section 24's warning that thinly-"
            "populated regimes refit noise, and it confirms the regime detector's "
            "value is in *interpretation* (panel, confidence), not as an extra "
            "goal-rate multiplier for this target."
        )
    lines.append("")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("\n" + "\n".join(lines[4:14]))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
