"""Data Fusion Layer on real data, across leagues and providers.

Independent providers describe the same fixtures (StatsBomb events,
football-data.co.uk official stats, openfootball community results). This
script runs the deterministic fusion pipeline end to end for every requested
league preset:

    entity resolution -> match resolution -> field comparison ->
    weighted fusion -> unified records + measured agreement rates
    -> measured per-source priors (the feedback loop, closed)

and writes validation/results/RESULTS_FUSION.md. The agreement tables are the
empirical per-source reliability; `priors_from_agreement` turns them into the
next run's priors deterministically.
"""

from __future__ import annotations

import argparse
import os

from fie.fusion import (
    agreement_report,
    fuse_match,
    priors_from_agreement,
    resolve_matches,
)
from fie.sources.providers import (
    FIELDS,
    FUSION_LEAGUES,
    PRIORS,
    load_league_sources,
)

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def fuse_league(key: str, cache_dir: str) -> dict:
    """Run the full pipeline for one league preset; return everything measured."""
    label = FUSION_LEAGUES[key]["label"]
    print(f"Loading sources for {label} ...")
    sources = load_league_sources(key, cache_dir)
    resolved = resolve_matches(sources)
    multi = [f for f in resolved if len(f["records"]) >= 2]
    full = [f for f in resolved if len(f["records"]) == len(sources)]
    counts = {name: len(records) for name, records in sorted(sources.items())}
    print(f"  {counts} -> 2+ sources: {len(multi)}, all {len(sources)}: {len(full)}")

    conflicts = []
    for fixture in multi:
        unified = fuse_match(fixture["records"], FIELDS, PRIORS)
        for field in unified["_conflicts"]:
            cell = unified[field]
            conflicts.append(
                f"{fixture['key'][0]} {fixture['key'][1]} vs {fixture['key'][2]} — "
                f"{field}: fused={cell['value']} (conf {cell['confidence']}, "
                f"dissent {cell['dissent']})"
            )
    return {
        "key": key, "label": label, "counts": counts,
        "n_sources": len(sources), "multi": multi, "n_full": len(full),
        "report": agreement_report(multi, FIELDS, PRIORS),
        "conflicts": conflicts,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--leagues", default=",".join(FUSION_LEAGUES),
                    help=f"comma-separated presets from {sorted(FUSION_LEAGUES)}")
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--out", default="validation/results/RESULTS_FUSION.md")
    args = ap.parse_args()

    leagues = [fuse_league(k.strip(), args.cache)
               for k in args.leagues.split(",") if k.strip()]

    # The feedback loop: measure per-source reliability across every league,
    # then re-fuse with the measured priors and count changed values.
    all_multi = [f for lg in leagues for f in lg["multi"]]
    measured = priors_from_agreement(all_multi, FIELDS, PRIORS)
    flips = 0
    for fixture in all_multi:
        before = fuse_match(fixture["records"], FIELDS, PRIORS)
        after = fuse_match(fixture["records"], FIELDS, measured)
        flips += sum(1 for f in FIELDS if before[f]["value"] != after[f]["value"])

    lines = [
        "# RESULTS (fusion) — Data Fusion Layer on real providers",
        "",
        "> Generated by `scripts/fuse_sources.py`. Deterministic pipeline: "
        "entity resolution -> match resolution -> weighted fusion "
        f"(configured priors {PRIORS}).",
        "",
    ]
    for lg in leagues:
        counts = " · ".join(f"{k}: **{v}**" for k, v in lg["counts"].items())
        lines += [
            f"## {lg['label']}",
            "",
            f"- Records: {counts}",
            f"- Fixtures resolved across 2+ sources: **{len(lg['multi'])}** · "
            f"across all {lg['n_sources']}: **{lg['n_full']}**",
            "",
            "| Field | Compared | Agreed | Rate |",
            "|---|---|---|---|",
        ]
        for field, s in lg["report"].items():
            lines.append(f"| {field} | {s['compared']} | {s['agreed']} | "
                         f"{s['rate'] if s['rate'] is not None else '—'} |")
        lines += ["", f"### Conflicts detected ({len(lg['conflicts'])})", ""]
        lines += [f"- {c}" for c in lg["conflicts"][:20]] or ["- none"]
        if len(lg["conflicts"]) > 20:
            lines.append(f"- … and {len(lg['conflicts']) - 20} more")
        lines.append("")

    lines += [
        "## Measured priors (the feedback loop, closed)",
        "",
        "`priors_from_agreement` scores each source against the fused majority "
        "over every compared field above — deterministic, one iteration:",
        "",
        "| Source | Configured prior | Measured reliability |",
        "|---|---|---|",
    ]
    for source, rate in measured.items():
        lines.append(f"| {source} | {PRIORS.get(source, 1.0)} | {rate} |")
    lines += [
        "",
        f"Re-fusing every fixture with the measured priors changes "
        f"**{flips}** fused values — the configured priors and the data "
        "currently tell the same story, which is itself a result.",
        "",
        "## Reading",
        "",
        "- **Goals should agree ~100%** — all providers watch the same "
        "scoreboard; any goal conflict would indicate an ingestion bug, so "
        "this doubles as an end-to-end data-quality check. It did: the "
        "majority vote on half-time scores exposed that our StatsBomb "
        "extraction missed own goals (separate `Own Goal For` events, not "
        "`Shot -> Goal`).",
        "- The half-time score (`ht_home`/`ht_away`) doubles as a **temporal "
        "anchor**: StatsBomb's value is reconstructed from period-1 events, "
        "so agreement validates the event clock against independent "
        "scoreboard providers.",
        "- **Corners/cards agreement measures definitional drift** between an "
        "event-collector (StatsBomb) and an official-stats aggregator "
        "(football-data). Disagreements are *information*: they are exactly "
        "the per-source reliability signal the fusion layer feeds on.",
        "- Every fused field carries provenance (which sources), a confidence "
        "(winning share of prior weight), and recorded dissent — nothing is "
        "silently overwritten.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"\nMeasured priors: {measured} (re-fusion flips: {flips})")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
