"""Phase 1 — ingest real StatsBomb matches, then backtest on real data.

Downloads a competition/season of free StatsBomb open data, maps it onto the
normalized Event model, writes everything to SQLite, runs the leakage-safe
backtest, and reports the **first real calibration** (Brier / log loss /
reliability) — the honest test of Section 20.2/20.4 on real football.

Usage:
    python scripts/ingest_statsbomb.py --competition 43 --season 3 --limit 30

Defaults to the 2018 FIFA World Cup (competition 43, season 3).
"""

from __future__ import annotations

import argparse
import os

from fie import db as fie_db
from fie.calibration import backtest, brier, log_loss, reliability_curve
from fie.events import state_from_events
from fie.indices import momentum_index
from fie.prediction import Params, rates
from fie.regime import detect_regime
from fie.sources.statsbomb import StatsBombSource

DEFAULT_CACHE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".sb_cache"
)


def _snapshots(conn, match, params, window=10, eval_step=5):
    events = match["events"]
    duration = match["duration"]
    for minute in range(eval_step, max(eval_step, duration - window) + 1, eval_step):
        events_until = [e for e in events if e.minute <= minute]
        state = state_from_events(match["match_id"], events, minute)
        regime = detect_regime(state, events_until, params)
        lam_home, lam_away = rates(state, events_until, params, regime=regime)
        mom = momentum_index(events_until, minute, params.tau)
        fie_db.insert_snapshot(
            conn, match["match_id"], minute, mom, regime, lam_home, lam_away
        )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--competition", type=int, default=43)
    ap.add_argument("--season", type=int, default=3)
    ap.add_argument("--limit", type=int, default=30, help="max matches to ingest")
    ap.add_argument("--db", default="fie_real.sqlite")
    ap.add_argument("--cache", default=DEFAULT_CACHE)
    ap.add_argument("--window", type=int, default=10)
    ap.add_argument("--out", default="validation/results/RESULTS_REAL.md")
    args = ap.parse_args()

    params = Params()
    conn = fie_db.connect(args.db)
    fie_db.init_schema(conn)

    print(f"Fetching match list for competition {args.competition}, season {args.season} ...")
    source = StatsBombSource(args.competition, args.season, cache_dir=args.cache)
    raw_matches = sorted(source.matches(), key=lambda m: m["match_id"])[: args.limit]

    matches = []
    total_goals = 0
    for i, raw in enumerate(raw_matches, 1):
        mid = raw["match_id"]
        try:
            match = source.match(mid)
        except Exception as exc:  # noqa: BLE001
            print(f"  [{i}/{len(raw_matches)}] match {mid}: download failed ({exc}); skipping")
            continue
        matches.append(match)
        total_goals += (match["home_score"] or 0) + (match["away_score"] or 0)
        fie_db.insert_match(conn, match, competition=str(args.competition), season=str(args.season))
        fie_db.insert_events(conn, match["match_id"], match["events"])
        _snapshots(conn, match, params, window=args.window)
        print(f"  [{i}/{len(raw_matches)}] {match['home_team']} {match['home_score']}"
              f"-{match['away_score']} {match['away_team']}  ({len(match['events'])} events)")
    conn.commit()

    if not matches:
        raise SystemExit("No matches ingested (network?).")

    # Leakage-safe backtest on real matches -> real calibration.
    result = backtest(matches, params, window=args.window)
    for record, (_, happened) in zip(result["predictions"], result["pairs"]):
        fie_db.insert_prediction(conn, record, happened)
    conn.commit()

    pairs = result["pairs"]
    real_brier = brier(pairs)
    real_logloss = log_loss(pairs)
    curve = reliability_curve(pairs, n_bands=10)
    base_rate_hit = sum(h for _, h in pairs) / len(pairs)
    goals_per_match = total_goals / len(matches)

    lines = [
        "# RESULTS (real data) — StatsBomb open data, Phase 1",
        "",
        f"> Generated by `scripts/ingest_statsbomb.py` on competition "
        f"{args.competition}, season {args.season} ({len(matches)} matches, "
        f"window {args.window} min). Leakage-safe backtest on real events.",
        "",
        f"- Matches ingested: **{len(matches)}**",
        f"- Real goals per match: **{goals_per_match:.2f}** (engine target ~2.7)",
        f'- Predictions scored ("goal in next {args.window} min"): **{len(pairs)}**',
        f"- Base frequency of the event: **{base_rate_hit:.3f}**",
        f"- **Brier: {real_brier:.4f}**   |   **Log loss: {real_logloss:.4f}**",
        "",
        "## Reliability curve (predicted vs observed)",
        "",
        "| Band predicted | Observed | N |",
        "|---|---|---|",
    ]
    for pred, obs, n in curve:
        lines.append(f"| {pred:.3f} | {obs:.3f} | {n} |")
    lines += [
        "",
        "> This is the honest Phase-3 test: it measures whether the heuristic "
        "probabilities are calibrated on real football. A gap from the diagonal is "
        "information, not failure — it is exactly what parameter fitting "
        "(Section 21) and per-regime calibration (Section 20) exist to close.",
        "",
    ]
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print("\n" + "\n".join(lines[3:12]))
    print(f"\nWrote {args.out} and {args.db}")


if __name__ == "__main__":
    main()
