"""Regenerate RESULTS.md from the Monte-Carlo experiments (Part G).

This file is generated, never hand-edited. It answers, mechanically and at a
glance, the question of Section 20.4: do the formulas, the regime logic, the
narrative verification, the consensus engine, and the calibration machinery work
as designed?
"""

from __future__ import annotations

import os

from _experiments import run_all


def _fmt(value):
    return f"{value:.4f}" if isinstance(value, float) else str(value)


def main():
    rows = run_all()
    lines = [
        "# RESULTS — Football Intelligence Engine mechanics validation",
        "",
        "> Generated by `scripts/report.py` — do not hand-edit. Reproduces the "
        "reference numbers quoted in `football_intelligence_engine.md` Section 20.4 "
        "and `validation_test_plan.md` Part C.",
        "",
        "| Test ID | Module | Type | Status | Observed | Target | Tolerance |",
        "|---------|--------|------|--------|----------|--------|-----------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['id']} | {r['module']} | {r['type']} | {r['status']} | "
            f"{_fmt(r['observed'])} | {_fmt(r['target'])} | ±{_fmt(r['tolerance'])} |"
        )
    lines += [
        "",
        "Run the full assertion suite (all test IDs in the plan) with:",
        "",
        "```bash",
        "pytest -q            # everything, including the slow Monte-Carlo tests",
        'pytest -q -m "not slow"   # fast feedback loop only',
        "```",
        "",
    ]

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "RESULTS.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    failed = [r["id"] for r in rows if r["status"] != "PASS"]
    print(f"Wrote {out} ({len(rows)} experiments).")
    if failed:
        print("FAILED:", ", ".join(failed))
        raise SystemExit(1)
    print("All experiments within tolerance.")


if __name__ == "__main__":
    main()
